# Part of the data deposit of 'Consecutive Powerful Numbers and Pell Equations' (B. Y. Sayim, 2026).
# License: Apache-2.0, see LICENSE and NOTICE.
#
# w115_walker_familien_2026-09-26.py
# Purpose: Walker families (`walker_familien`): pairs (n, n+1) of powerful numbers in which NEITHER is a square. For every
#   squarefree D = b*d <= DMAX (b, d >= 2, every ordered factorization) it decides whether d*X^2 - b*Y^2 = 1 has solutions with b
#   | Y and d | X (so that n = b*Y^2 and n+1 = d*X^2 are both powerful), generates all such pairs up to XMAX, and checks them
#   independently.
# Reads: skripte/w114_a060355_quelle_2026-09-26.py (imported as a module: the list of terms of OEIS A060355, the source label),
#   ergebnisse/w111_paar_familien_result.json. Requires SymPy.
# Writes: ergebnisse/w115_walker_familien_result.json and ergebnisse/w115_walker_familien_output.txt (for DMAX != 100000 the names
#   carry the suffix _D<DMAX>, so the canonical files stay untouched).
# Usage: python w115_walker_familien_2026-09-26.py [DMAX]   (default 100000)
# Controls: PK0, PK1, PK2, PK3, independent factorization of every generated pair, and a negative control NK (see below).

# Use: the lower bound liminf N(x)/ln x >= sum 1/ln F of Part II is supplemented by the families without a square (so far only the
#   square families were included, w112/w113). The pairs are generated by our own computation, independently of the OEIS list.
#
# Search space (fixed in advance, before any comparison with OEIS A060355): all squarefree D = b*d <= DMAX = 10^5 with b, d >= 2,
#   every ordered factorization (no choice made after the known pairs). All terms with n + 1 <= XMAX = term 39 + 1 ~ 3.89*10^21
#   are generated (the value comes from w114).
#
# Mathematics: n = b*Y^2, n + 1 = d*X^2, where b is the squarefree part of n and d that of n + 1 (coprime, D = b*d squarefree).
#   n powerful <=> b | Y, n + 1 powerful <=> d | X. Equation d*X^2 - b*Y^2 = 1. With ε = x₁ + y₁√D (smallest solution of
#   x² − D·y² = 1):
#   CLAIM A: if d·X² − b·Y² = 1 is solvable, then for the smallest solution α = X₀√d + Y₀√b one has α² = ε, i.e. x₁ + 1 = 2d·X₀²,
#     x₁ − 1 = 2b·Y₀². Proof sketch: α² has norm 1 in ℤ[√D] ⇒ α² = ε^j. j even ⇒ α ∈ ℤ[√D]·(±1), impossible (d > 1). j = 2i+1 ≥ 3
#     ⇒ α·ε^(−i) is a smaller positive solution of the same form ⇒ contradiction. ⇒ j = 1. — Not assumed but checked by brute
#     force in PK0.
#   All solutions: α·ε^k, k ≥ 0:  X_{k+1} = x₁X_k + b·y₁Y_k,  Y_{k+1} = x₁Y_k + d·y₁X_k.
#   DIVISIBILITY: for a prime p | b one has X_{k+1} ≡ x₁X_k (mod p) and x₁² ≡ 1 ⇒ s := x₁ mod p ∈ {±1}; by induction
#     Y_k ≡ s^k·Y₀ + k·s^(k−1)·d·y₁·X₀ (mod p) ⇒ p | Y_k ⟺ s·Y₀ + k·d·y₁·X₀ ≡ 0 (mod p)  (p ∤ d, p ∤ X₀ because d·X₀² ≡ 1).
#     ⇒ either p | y₁: always (p | Y₀) or never; otherwise exactly one residue class of k mod p.
#     For q | d symmetrically, with X in place of Y.
#   ⇒ the valid k form ONE residue class k ≡ k₀ (mod M), M | D (Chinese remainder theorem), or there is no family.
#   Birth t = ln n_{k₀} ≈ 2·ln α + 2k₀·ln ε − ln 4 (log of the first member); growth per member ln F = 2M·ln ε.
#   The formula is checked against direct iteration in PK1.
#
# Controls:
#   PK0 Claim A by brute force (D <= 300, X <= 2·10⁴) · PK1 residue-class formula against iteration modulo b·d
#   (D <= 3000, k < 3M) · PK2 Golomb's pair (12167, 12168) = family (23, 2) and Walker's 7³x² = 3³y² + 1 = family (3, 7) must
#   appear · PK3 all pairs without a square of OUR OWN list up to 2⁵² (w107/w111, terms 1–26) must be generated ·
#   INDEPENDENTLY every generated pair <= XMAX by complete factorization (sympy as a black box) · NK the member k₀ + 1 of a
#   family with M > 1 must NOT be a pair.
#   Only AFTER that: comparison with the terms 27–39 of A060355 (values via w114, output shows only the numbers) — in both
#   directions.
#
# Expectations (stated before the run): E1 PK0 without deviation. E2 at most ONE solvable ordered factorization per D
#   [assumption, classical; it is counted]. E3 families without a square with birth <= 3.9·10²¹: few, at most as many as pairs
#   without a square in the list (7) [assumption]. E4 Σ 1/ln F of these families for D <= 10⁵: small against 1.3307 of the
#   square families, about 0.05–0.3 [assumption: M | D mostly large, ε large]. E5 all 7 pairs without a square of the list lie
#   in families with D <= 10⁵ [assumption, falsifiable].

import sys, json, math, time, pathlib, importlib.util
from math import isqrt, gcd, log
import sympy
sys.stdout.reconfigure(encoding='utf-8')
HIER = pathlib.Path(__file__).resolve().parent; ERG = HIER.parent/'ergebnisse'   # script folder; results folder
aus = []   # `aus` = output lines, written to the _output.txt file
def sag(s=''):   # `sag` = say: print a line and record it in `aus`
    print(s, flush=True); aus.append(s)
t_start = time.time()
DMAX = int(sys.argv[1]) if len(sys.argv) > 1 else 100_000   # `DMAX` = largest D = b*d
TAG = '' if DMAX == 100_000 else f'_D{DMAX}'   # a different bound writes its own files; the canonical ones (10⁵) stay untouched
sag('='*100); sag(f'w115 — WALKER-FAMILIEN (kein Quadrat im Paar), D = b·d ≤ {DMAX:,}   ' + time.strftime('%Y-%m-%d %H:%M')); sag('='*100)
_s = importlib.util.spec_from_file_location('w114', HIER/'w114_a060355_quelle_2026-09-26.py')
w114 = importlib.util.module_from_spec(_s); _s.loader.exec_module(w114)
# `A` = terms of A060355 (via `w114.glieder`), `XMAX` = last term + 1, `LX` = ln XMAX
A = w114.glieder(); XMAX = A[-1] + 1; LX = log(XMAX)

def pell(m):                                   # smallest solution of x² − m·y² = 1 (continued fraction), as in w113
    a0 = isqrt(m); P, Q, a = 0, 1, a0; h1, h0, k1, k0 = 1, a0, 0, 1
    while True:
        if h0*h0 - m*k0*k0 == 1: return h0, k0
        P = a*Q - P; Q = (m - P*P)//Q; a = (a0 + P)//Q
        h1, h0 = h0, a*h0 + h1; k1, k0 = k0, a*k0 + k1
# `ist_quadrat` = is a square: the integer square root if z is a perfect square, else None
def ist_quadrat(z):
    if z < 0: return None
    r = isqrt(z); return r if r*r == z else None
def ln_eps(x, y, m):                           # ln of ε = x + y·√m without overflow
    return log(x) + (log(2) if x > 10**12 else log(1 + y*math.sqrt(m)/x))
spf = list(range(DMAX + 1))                    # smallest prime factor of every number up to DMAX
for p in range(2, isqrt(DMAX) + 1):
    if spf[p] == p:
        for q in range(p*p, DMAX + 1, p):
            if spf[q] == q: spf[q] = p
def primfaktoren_qf(D):                        # prime factors if D is squarefree (`qf` = quadratfrei), else None
    ps = []
    while D > 1:
        p = spf[D]; D //= p
        if D % p == 0: return None
        ps.append(p)
    return ps
# `zerlegungen` = factorizations: ordered factorizations D = b·d with b, d ≥ 2 (all proper non-empty subsets of the primes)
def zerlegungen(ps):
    r = len(ps)
    for mask in range(1, 2**r - 1):
        b = math.prod(ps[i] for i in range(r) if mask >> i & 1); yield b, math.prod(ps) // b
# `restklasse` = residue class: (k0, M) or None (no family); see the divisibility argument above
def restklasse(b, d, x1, y1, X0, Y0):
    res = []
    for p in primfaktoren_qf(b):
        s = x1 % p; c = (d*y1*X0) % p
        if c == 0:
            if Y0 % p: return None
            continue
        res.append(((-s*Y0*pow(c, -1, p)) % p, p))
    for q in primfaktoren_qf(d):
        s = x1 % q; c = (b*y1*Y0) % q
        if c == 0:
            if X0 % q: return None
            continue
        res.append(((-s*X0*pow(c, -1, q)) % q, q))
    k0, M = 0, 1
    for r, p in res:                            # Chinese remainder theorem, moduli pairwise distinct (D squarefree)
        k0 = (k0 + M*((r - k0)*pow(M, -1, p) % p)) % (M*p); M *= p
    return k0, M

# ---------------------------------------------------------------- PK0: Claim A by brute force
# smallest X <= XB with (d·X² − 1)/b a perfect square Y²: returns (X, Y) or None
def brute(b, d, XB):
    for X in range(1, XB + 1):
        if (d*X*X - 1) % b == 0:
            Y = ist_quadrat((d*X*X - 1)//b)
            if Y: return X, Y
    return None
# counters: `pk0_n` = ordered factorizations tested, `pk0_ok` = agreements, `pk0_loesb` = solvable ones
pk0_ok = pk0_n = pk0_loesb = 0
for D in range(6, 301):
    ps = primfaktoren_qf(D)
    if not ps or len(ps) < 2: continue
    x1, y1 = pell(D)
    for b, d in zerlegungen(ps):
        pk0_n += 1
        X0 = ist_quadrat((x1 + 1)//(2*d)) if (x1 + 1) % (2*d) == 0 else None
        Y0 = ist_quadrat((x1 - 1)//(2*b)) if (x1 - 1) % (2*b) == 0 else None
        # `a_form` = solution predicted by Claim A
        a_form = (X0, Y0) if X0 and Y0 is not None and d*X0*X0 - b*Y0*Y0 == 1 else None
        bf = brute(b, d, 20_000)
        if a_form: pk0_loesb += 1
        if (bf == a_form) or (bf is None and a_form and a_form[0] > 20_000): pk0_ok += 1
        else: sag(f'   🔴 PK0 Abweichung bei (b, d) = ({b}, {d}): Brute {bf} · aus ε {a_form}')
sag(f'PK0 Behauptung A (α² = ε), D ≤ 300, alle {pk0_n} geordneten Zerlegungen, Brute Force bis X = 2·10⁴: '
    f'{pk0_ok}/{pk0_n} gleich {"✅" if pk0_ok == pk0_n else "🔴"} ({pk0_loesb} loesbar)')
assert pk0_ok == pk0_n

# ---------------------------------------------------------------- main run
# `fam` = families found; `mehrfach` = number of D with more than one solvable ordered factorization; `pk1_n`, `pk1_ok` = PK1
#   tests and agreements; `loesbar_D` = number of D with a solvable factorization; `treffer` = solvable factorizations of the
#   current D
fam = []; mehrfach = 0; pk1_n = pk1_ok = 0; loesbar_D = 0
for D in range(6, DMAX + 1):
    ps = primfaktoren_qf(D)
    if not ps or len(ps) < 2: continue
    x1, y1 = pell(D); le = None; treffer = 0
    for b, d in zerlegungen(ps):
        if (x1 + 1) % (2*d) or (x1 - 1) % (2*b): continue
        X0 = ist_quadrat((x1 + 1)//(2*d)); Y0 = ist_quadrat((x1 - 1)//(2*b))
        if not X0 or Y0 is None or d*X0*X0 - b*Y0*Y0 != 1: continue
        treffer += 1
        rk = restklasse(b, d, x1, y1, X0, Y0)
        # PK1: formula against iteration modulo b·d (`gut` = valid k found by iterating, `soll` = valid k by the formula)
        if D <= 3000:
            L = b*d; M_ = rk[1] if rk else D
            X, Y = X0 % L, Y0 % L; gut = []
            for k in range(3*M_):
                if Y % b == 0 and X % d == 0: gut.append(k)
                X, Y = (x1*X + b*y1*Y) % L, (x1*Y + d*y1*X) % L
            soll = [k for k in range(3*M_) if rk and k % rk[1] == rk[0]]
            pk1_n += 1; pk1_ok += (gut == soll)
            if gut != soll: sag(f'   🔴 PK1 ({b}, {d}): Iteration {gut[:6]} · Formel {soll[:6]}')
        if rk is None: continue
        k0, M = rk
        if le is None: le = ln_eps(x1, y1, D)
        # `la` = ln α; Y0√b ≈ X0√d; no float overflow
        la = log(X0) + 0.5*log(d) + (log(2) if X0 > 10**12 else log(1 + (Y0*math.sqrt(b))/(X0*math.sqrt(d))))
        t = 2*la + 2*k0*le - log(4); lnF = 2*M*le   # `t` = birth, `lnF` = ln F (growth per member)
        fam.append(dict(b=b, d=d, D=D, M=M, k0=k0, t=t, lnF=lnF, x1=x1, y1=y1, X0=X0, Y0=Y0))
    if treffer: loesbar_D += 1
    mehrfach += treffer > 1
    if D % 20_000 == 0: sag(f'   … D = {D:,}: {len(fam)} Familien, {time.time() - t_start:.0f} s')
sag(f'PK1 Restklassen-Formel gegen Iteration mod b·d (D ≤ 3000): {pk1_ok}/{pk1_n} {"✅" if pk1_ok == pk1_n else "🔴"}')
assert pk1_ok == pk1_n
sag(f'E2 je D hoechstens eine loesbare geordnete Zerlegung: D mit mehreren = {mehrfach} {"✅" if mehrfach == 0 else "⚠️"} · loesbare D: {loesbar_D}')
sag(f'Familien ohne Quadrat (Teilbarkeit erfuellbar): {len(fam)}')

# ---------------------------------------------------------------- generate the pairs up to XMAX + check them independently
# `glied` = member k of family f: α·ε^k by repeated squaring; returns (X_k, Y_k)
def glied(f, k):
    X, Y = f['X0'], f['Y0']; x1, y1, b, d = f['x1'], f['y1'], f['b'], f['d']
    ex, ey, e = x1, y1, k                       # α·ε^k by squaring
    PX, PY = 1, 0
    while e:
        if e & 1: PX, PY = PX*ex + f['D']*PY*ey, PX*ey + PY*ex
        ex, ey = ex*ex + f['D']*ey*ey, 2*ex*ey; e >>= 1
    return X*PX + b*Y*PY, Y*PX + d*X*PY        # (X_k, Y_k)
def powerful(n):
    return all(e >= 2 for e in sympy.factorint(n).values())
paare = {}; nk_n = nk_ok = 0   # `paare` = generated pairs: n -> (b, d); `nk_n`, `nk_ok` = negative-control tests and passes
for f in fam:
    if f['t'] > LX + 1: continue
    k = f['k0']
    while True:
        X, Y = glied(f, k); n = f['b']*Y*Y
        if n + 1 > XMAX: break
        assert f['d']*X*X == n + 1 and Y % f['b'] == 0 and X % f['d'] == 0
        paare[n] = (f['b'], f['d'])
        k += f['M']
    # NK: the member directly after k0 must not be a pair — checked directly on n (p² | n for p | b, etc.)
    if f['M'] > 1:
        X, Y = glied(f, f['k0'] + 1); n = f['b']*Y*Y
        paar = all(n % (p*p) == 0 for p in primfaktoren_qf(f['b'])) and all((n + 1) % (q*q) == 0 for q in primfaktoren_qf(f['d']))
        nk_n += 1; nk_ok += not paar
# `unab` = independent check: both n and n + 1 powerful for every generated pair
unab = all(powerful(n) and powerful(n + 1) for n in paare)
sag(f'Erzeugte Paare ohne Quadrat mit n + 1 ≤ 3,89·10²¹: {len(paare)} · unabhaengig vollfaktorisiert, beide powerful: {"✅" if unab else "🔴"}'
    f' · NK Glied k₀ + 1 kein Paar: {nk_ok}/{nk_n} {"✅" if nk_ok == nk_n else "🔴"}')
assert unab and nk_ok == nk_n
pk2 = {12167: (23, 2)}
walker_fam = any(f['b'] == 3 and f['d'] == 7 for f in fam)   # PK2: Walker's family (3, 7) is present
sag(f'PK2 Golomb 12167 → Familie (23, 2): {"✅" if paare.get(12167) == (23, 2) else "🔴"} · Walkers 7³x² = 3³y² + 1 → Familie (3, 7) vorhanden: '
    f'{"✅" if walker_fam else "🔴"}')
assert paare.get(12167) == (23, 2) and walker_fam
w111 = json.load(open(ERG/'w111_paar_familien_result.json', encoding='utf-8'))
# `eigene_w` = pairs without a square among our own terms
eigene_w = [int(p['n']) for p in w111['paare'] if p['i'] <= w114.EIGENE and p['b'] > 1 and p['d'] > 1]
fehlt_e = [n for n in eigene_w if n not in paare]   # `fehlt_e` = missing: those not generated here (must be empty)
sag(f'PK3 Paare ohne Quadrat der EIGENEN Liste bis 2⁵² (w107/w111): {len(eigene_w) - len(fehlt_e)}/{len(eigene_w)} erzeugt '
    f'{"✅" if not fehlt_e else "⚠️ fehlen: " + str(fehlt_e)}')

# ---------------------------------------------------------------- ONLY NOW: comparison with A060355 (terms 27–39), numbers only
# `fremd_w` = foreign terms: terms 27–39 of the list that are pairs without a square
fremd_w = [(p['i'], p['b'], p['d']) for p in w111['paare'] if p['i'] > w114.EIGENE and p['b'] > 1 and p['d'] > 1]
v_hin = [(i, A[i - 1] in paare) for i, b, d in fremd_w]   # direction 1: is the listed term generated here?
listen = set(A)   # `listen` = the terms of the list as a set
neu = sorted(n for n in paare if n not in listen)          # direction 2: generated here but not in the list
sag(f'VERGLEICH A060355, Glieder 27–39 ohne Quadrat: ' + ' · '.join(f'Glied {i} {"✅ selbst erzeugt" if ok else "— nicht im Suchraum"}' for i, ok in v_hin))
sag(f'   umgekehrt: selbst erzeugte Paare ohne Quadrat ≤ 3,89·10²¹, die NICHT in den 39 Gliedern stehen: {len(neu)}'
    + (' ✅' if not neu else ' 🔴 — sofort pruefen: ' + ', '.join(str(n) for n in neu[:5])))

# ---------------------------------------------------------------- lower bound
treppe = {}   # `treppe` = staircase: Σ 1/ln F over the families with D <= B
for B in (10**3, 10**4, 10**5, 10**6):
    if B <= DMAX: treppe[str(B)] = sum(1/f['lnF'] for f in fam if f['D'] <= B)
sag(f'Σ 1/ln F ueber die Familien ohne Quadrat: ' + ' · '.join(f'D ≤ 10^{len(k) - 1}: {v:.4f}' for k, v in treppe.items()))
geb = sorted(fam, key=lambda f: f['t'])[:12]   # `geb` = the twelve earliest births
sag('Die zwoelf frühesten Geburten (b, d; ln n der ersten Stelle; Periode M; ln F):')
for f in geb: sag(f'   ({f["b"]}, {f["d"]})  D = {f["D"]:>6}  t = {f["t"]:9.3f}  M = {f["M"]:>6}  ln F = {f["lnF"]:.3f}')
dauer = time.time() - t_start
# `res` = result dict: `skript` = script name, `datum` = date, `quelle_vergleich` = source of the comparison list,
#   `mehrfach_loesbare_D` = D with several solvable factorizations, `familien` = number of families, `paare_ohne_quadrat_bis_XMAX`
#   = pairs without a square up to XMAX, `vergleich_glieder_27_39` = comparison for the terms 27–39 (`glied` = term,
#   `selbst_erzeugt` = generated by us), `nicht_in_liste` = generated but not in the list, `summe_1_durch_lnF` = sums of 1/ln F,
#   `frueheste` = earliest births, `laufzeit_s` = run time in seconds (`dauer` = duration)
res = dict(skript=pathlib.Path(__file__).name, datum=time.strftime('%Y-%m-%d %H:%M'), DMAX=DMAX, quelle_vergleich=w114.QUELLE,
           pk0=[pk0_ok, pk0_n], pk1=[pk1_ok, pk1_n], mehrfach_loesbare_D=mehrfach, familien=len(fam),
           # OUR OWN computation (no values taken over from the list)
           paare_ohne_quadrat_bis_XMAX=[str(n) for n in sorted(paare)],
           vergleich_glieder_27_39=[dict(glied=i, selbst_erzeugt=ok) for i, ok in v_hin], nicht_in_liste=[str(n) for n in neu],
           summe_1_durch_lnF=treppe, frueheste=[dict(b=f['b'], d=f['d'], D=f['D'], t=round(f['t'], 4), M=f['M'], lnF=round(f['lnF'], 4)) for f in geb],
           laufzeit_s=round(dauer))
(ERG/f'w115_walker_familien{TAG}_result.json').write_text(json.dumps(res, indent=1, ensure_ascii=False), encoding='utf-8')
(ERG/f'w115_walker_familien{TAG}_output.txt').write_text('\n'.join(aus) + '\n', encoding='utf-8')
sag(f'Laufzeit {dauer:.0f} s')
