\\ Part of the data deposit of 'Consecutive Powerful Numbers and Pell Equations' (B. Y. Sayim, 2026).
\\ License: Apache-2.0, see LICENSE and NOTICE.
/* pari_pruefen.gp
   Second check of our own ECPP certificates by PARI's built-in verifier primecertisvalid (PARI/GP 2.17.2, run in a container).
   Reads:   /par/cert_1.txt (a certificate generated by PARI), /in/e5_cert_<i>_eigen.txt (our certificates, Part I, i = 1..6),
            /in/e5_cert_t2_<i>_eigen.txt (our certificates, Part II, i taken from the list L).
   Writes:  nothing; prints one line per check and a final summary line to standard output.
   Usage:   gp with this file as script, with the certificate files mounted at /par and /in.
   Controls: PK: the PARI-generated certificate must be valid. NK: the same certificate with t shifted by 1 must be invalid.
   primecertisvalid returns 1 for a valid certificate. */
default(parisizemax, 1500000000);
default(nbthreads, 1);
pk = read("/par/cert_1.txt");
print("PK PARI-Zertifikat Teil I Nr. 1: ", iferr(primecertisvalid(pk), E, "FEHLER"));
nk = pk; nk[1][2] += 1;
print("NK verschobenes t: ", iferr(primecertisvalid(nk), E, "FEHLER (Ausnahme)"));
n = 0; ok = 0;
for(i = 1, 6, f = Str("/in/e5_cert_", i, "_eigen.txt"); C = read(f); r = iferr(primecertisvalid(C), E, -1); n++; if(r == 1, ok++); print("Teil I Nr. ", i, " (", #Str(C[1][1]), " Stellen, ", #C, " Schritte): ", r));
L = [1,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19];
for(k = 1, #L, i = L[k]; f = Str("/in/e5_cert_t2_", i, "_eigen.txt"); C = read(f); r = iferr(primecertisvalid(C), E, -1); n++; if(r == 1, ok++); print("Teil II Nr. ", i, " (", #Str(C[1][1]), " Stellen, ", #C, " Schritte): ", r));
print("ERGEBNIS: ", ok, " von ", n, " Eigenbau-Zertifikaten von PARI als gueltig bestaetigt");
